import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" >
        <body className={inter.className}>
          <div className="container mx-auto px-4 py-8">
           <NavBar />
            <hr />
            {children}
          </div>

        </body>
      </html>
    </ClerkProvider>
  )
}
